apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cccctw747-python 
  janus-idp.io/tekton: cccctw747-python
  backstage.io/kubernetes-id: cccctw747-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cccctw747-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  